### PR TITLE
AXBY is all the same

### PR DESCRIPTION
**Pull request by kevintsang97**
Should work properly with changes to `sound_field_vr_instruct.py` now. AXBY are all buttons to check.

### CODE REVIEW

**Review by djmannion — COMMENTED** [review]
I don't think these changes are necessary?

**Comment by kevintsang97** [comment]
I thought this was the way to change the default, so I don't need to put `any_button=True` in each ```_draw_screen```?

**Comment by djmannion** [comment]
I meant to change the default in the `_draw_screen` definition, so that you don't need to specify it in each `_draw_screen` call.

**Comment by djmannion** [comment]
Your changes here make it so that it always checks all buttons, even if `any_button` is `False`.

**Pull request closed without merging**
